### PR TITLE
npm install current lib before travis, example scripts

### LINKED ISSUE #261: AOT issue
Hi,

Since the last version 3.3.1, i m having this error when building my app in aot:

`ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 77:13 in the original .ts file), resolving symbol action in /Users/xxx/node_modules/mobx/lib/mobx.d.ts, resolving symbol TreeNodeCollectionComponent in /Users/xxx/node_modules/angular-tree-component/dist/components/tree-node-collection.component.d.ts
`

### PR DESCRIPTION
**Pull request by jskrzypek**
Fixes #261

`action` should be imported from `mobx-angular` so we get the decorator metadata for angular AOT

This pr also adds an example with a mobx strict mode to facilitate testing.

### CODE REVIEW

**Comment by queejie** [comment]
I believe this error is preventing me from moving to Angular 4.  Is there a workaround now, or a fix on the near horizon?  Here is the message I'm getting:

``ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 78:13 in the original .ts file), resolving symbol action in /Users/dqj/Local/dev/apps/pl3/pepe/frontend/node_modules/mobx/lib/mobx.d.ts, resolving symbol TreeNodeCollectionComponent in /Users/dqj/Local/dev/apps/pl3/pepe/frontend/node_modules/angular-tree-component/dist/components/tree-node-collection.component.d.ts
``

Thank you.

**Comment by jskrzypek** [comment]
I'd suggest installing & fixing the dep to 3.3.0 for now until this lands

**Comment by ghaiat** [comment]
Hello, can you merge the PR  ?

**Comment by ghaiat** [comment]
can anyone merge this please?

**Comment by adamkleingit** [comment]
Hi @jskrzypek ,

I will add useStrict to the main example.
importing action from mobx-angular already solved in a different branch.

Can you leave only the travis fix and I will merge? Thanks

**Comment by jskrzypek** [comment]
I'm leaving the `npm i ../..` changes in the package.json scripts as well, since I believe that's what you intended

**Comment by jskrzypek** [comment]
@adamkleingit Please let me know if you need anything else changed

**Pull request merged**
