### PR TITLE
Better tree shaking with specific imports from lodash, take 2

### PR DESCRIPTION
**Pull request by BahjatSalem**
This is a (slightly cleaner) version of PR #372 (closed).

Instead of doing (for example)
`import * as _ from 'lodash';`
we're doing a 
`import defaultsDeep from 'lodash-es/defaultsDeep';`
and then using `defaultsDeep` directly. This helps rollup in the tree-shaking process.

### CODE REVIEW

**Comment by adamkleingit** [comment]
I ran the build process and the UMD was 75KB after the pull request instead of 50KB before it.
Have you tested this?

**Comment by mtraynham** [comment]
@adamkleingit Using webpack and a variety of lodash functions myself, this is somewhat of a pain point using angular-tree-component.  The WebpackBundleAnalyzer gives a pretty good overview of how much the full lodash dependency is adding to the bundle (below).

I use the same lodash npm dependency myself, not lodash-es.  But instead I import only the utilities I need as represented in this initial PR.

Instead of:
```ts
import {groupBy} from 'lodash';
```

Do:
```ts
import groupBy from 'lodash/groupBy';
```

This is shown by the same lodash dependency in the picture represented below, but is the smaller and more numerous tree set of modules within that giant lodash dependency.  Unfortunately doesn't look @BahjatSalem has responded to you, so would you prefer another PR?

screen shot 2018-01-04 at 9 40 58 am

**Comment by BahjatSalem** [comment]
Actually, I managed to reach my tree-shaking goals using `babel-plugin-lodash`, used without the `es2015` presets.

**Comment by mtraynham** [comment]
Ehh, I don't know if that's a great solution.  It works, but it only works for babel users; strictly TS users don't benefit.  Also for webpack builds, you have to start using the babel-loader against node_modules which can be somewhat timely when the library should already be distributed in a format that is consumable by any # of environments.

**Comment by BahjatSalem** [comment]
I'm not sure if I qualify as a "babel user", but I do know that I _only_ use babel for `babel-plugin-lodash`.
Here's an excerpt of our `rollup.config.js`:
```
import babel from 'rollup-plugin-babel';
// [...]
export default {
    // [...]
    plugins: [
        babel({
            include: 'node_modules/angular-tree-component/**',
            babelrc: false,
            plugins: ['lodash']
        }),
        // Other plugins go here
    ]
};
```
I can't really help you with webpack, but you have many options. Google is your friend.

**Comment by cipchk** [comment]
so regretful that great PR.

**Pull request closed without merging**
