### PR TITLE
Uniform html structure for nodes with and without children

### PR DESCRIPTION
**Pull request by JulienNexonia**
Uniform html structure for nodes with and without children
Add same wrapper for both with or without children

### CODE REVIEW

**Comment by adamkleingit** [comment]
Hi,
this is not backwards compatible as it changes the HTML Structure.
Can you specify why this is necessary?

Thanks

**Comment by JulienNexonia** [comment]
Hi,
If is necessary to get the same behavior between nodes with an dwithout children.
As you can see on the attachment, the borders are not aligned for the last leaf.
sans titre

**Comment by adamkleingit** [comment]
Are you using the latest version of the tree? Can you share your CSS for the tree?
In the default tree style the nodes are aligned, both childless and parents.
If you add custom CSS, you can also add custom padding to the toggle-children-placeholder.

**Comment by JulienNexonia** [comment]
I am currently using version 2.6.0.
Here is the code : 
```
<div id="tree-container">
    <Tree
      class="tree"
      #tree
      [nodes]="nodes"
      [focused]="true"
      [options]="customOptions"
      (onEvent)="onEvent($event)"
      (onUpdateData)="onUpdateData($event)">
      <template #treeNodeTemplate let-node>

        <div class="node-div">
          <div class="node-content-div" (click)="selectNode(node)">
            <div class="node-content-text-div">
              <span title="{{node.data.subTitle}}" class={{node.data.classe}}>{{node.data.name}}</span>
            </div>
          </div>
        </div>

      </template>
      <template #loadingTemplate>Loading...</template>
    </Tree>
  </div>
```

Here is the css : 
```
.node-content-wrapper iron-icon {
  color: $primary-color;
}

treenode, .tree, .tree-node, .node-wrapper, .node-content-wrapper {
  width: 100%;
}

.tree-node-active.tree-node-focused > .node-wrapper > .node-content-wrapper {
  background: rgba(51, 121, 183, 0.15) !important;
}

.node-content-text-div > span:hover,
.tree-node-active.tree-node-focused > .node-wrapper > .node-content-wrapper > treenodecontent > .node-div > .node-content-div > .node-content-text-div > span {
  color: $primary-color;
}

.node-content-wrapper, .tree-children {
  position: relative;
}

.node-content-wrapper::before, .tree-children::after {
  content: "";
  position: absolute;
}

.node-content-wrapper::before {
  border-bottom: 1px solid $border-color;
  border-left: 1px solid $border-color;
  height: 28px;
  top: -17px;
  width: 20px;
  left: -28px;
}

.tree-node-leaf > .node-wrapper > .node-content-wrapper::before {
  width: 25px;
}

.tree-children::after {
  border-left: 1px solid $border-color;
  height: 100%;
  top: -15px;
  left: -15px;
}

treenode:last-child > .tree-node > .tree-children::after {
  border-left: none;
}

.toggle-children {
  z-index: 1;
}

#tree-container {
  background-color: $primary-background-color;
  overflow: auto;
  border-top: 1px solid $border-color;
  padding: 10px 25px 10px 10px;
  flex: 100;
}

// Node div
.node-div {
  display: inline-flex;
  width: 100%;
}

// Node content
.node-content-div {
  display: inline-flex;
  width: 100%;
}

// Node content text
.node-content-text-div {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  display: inline;
  //width:100%;
}

```

I am using the splitlayout from vaadin to update the layout of the tree as follows:

> |Tree **|||** Form|

The bar '|||' is the middle is horizontally draggable to allow less/more space to tree or form component.
(https://vaadin.com/elements/-/element/vaadin-split-layout)
The descibed behavior seems only to happen when I slide the bar to the left to reduce the tree.

When I add an empty html element to simulate the exact same html structure for both cases (with/without children), everything works perfectly.

Happy new year ;-)
Julien

**Comment by DrMabulle** [comment]
+1
I have a similar problem...

**Comment by nicolasFauren** [comment]
+1 !!

**Comment by adamkleingit** [comment]
I'll look into it ASAP

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by adamkleingit** [comment]
Hey @nicolasFauren @DrMabulle @JulienNexonia ,
a lot has changed since this PR.

Does the new structure have the same problem? Thanks

**Comment by adamkleingit** [comment]
Closing this as the structure already changed and we now have 3 levels of templates

**Pull request closed without merging**
