### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by monkeywithacupcake**
Hi, I'm making updates for Open Collective. Either you or another core contributor signed this repository up for Open Collective. This pull request adds financial contributors from your Open Collective https://opencollective.com/angular-tree-component ❤️

  What it does:
  - adds a badge to show the latest number of financial contributors
  - adds a banner displaying contributors to the project on GitHub
  - adds a banner displaying all individuals contributing financially on Open Collective
  - adds a section displaying all organizations contributing financially on Open Collective, with their logo and a link to their website

We have also added a `postinstall` script to let people know after `npm|yarn install` that you are welcoming donations. Feel free to remove it if you don't want it. [[More info](https://github.com/opencollective/opencollective-postinstall)]

P.S: As with any pull request, feel free to comment or suggest changes.

  Thank you for your great contribution to the Open Source community. You are awesome! 🙌
  And welcome to the Open Collective community! 😊

  Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other Open Source sustainers!

### CODE REVIEW

**Comment by dtomasbar** [comment]
Hey, I got this error while installing version 8.5.2:
> angular-tree-component@8.5.2 postinstall C:\Users\danie\Desktop\BL-GIT\platforms\bigle-plataform\node_modules\angular-tree-component
> opencollective-postinstall || true

"opencollective-postinstall" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"true" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

I solved it by downgrading to 8.4.0

Right now is not an issue for me because we are not using this component, but if I can do anything to help you solve it let me know

Bests

**Comment by adamkleingit** [comment]
Hi @dtomasbar, what operating system are you using? which version? And which version of node?
@monkeywithacupcake - do you know this error?

**Comment by dtomasbar** [comment]
Hi @adamkleingit  I am using Windows 10

Here are all my dependencies:
`{
  "dependencies": {
    "@angular/animations": "8.2.14",
    "@angular/cdk": "8.2.3",
    "@angular/common": "8.2.14",
    "@angular/compiler": "8.2.14",
    "@angular/core": "8.2.14",
    "@angular/fire": "5.2.3",
    "@angular/forms": "8.2.14",
    "@angular/material": "8.2.3",
    "@angular/platform-browser": "8.2.14",
    "@angular/platform-browser-dynamic": "8.2.14",
    "@angular/pwa": "0.803.20",
    "@angular/router": "8.2.14",
    "@angular/service-worker": "8.2.14",
    "@bigle/entities": "github:biglelegal/entities#v1.0.47",
    "@bigle/written-number": "github:biglelegal/js-written-number#v1.0.4",
    "@swimlane/ngx-charts": "12.1.0",
    "@swimlane/ngx-datatable": "16.0.2",
    "@types/file-saver": "^2.0.1",
    "@types/string-similarity": "3.0.0",
    "@webcomponents/webcomponentsjs": "2.4.0",
    "ang-jsoneditor": "1.8.4",
    "angular-tree-component": "8.5.2",
    "angular2-collapsible": "0.6.1",
    "angular2-fontawesome": "5.2.1",
    "angular2-moment": "1.9.0",
    "angular2-multiselect-dropdown": "4.6.3",
    "angular2-prettyjson": "3.0.1",
    "ckeditor": "4.12.1",
    "classlist.js": "1.1.20150312",
    "core-js": "3.5.0",
    "d3": "5.14.2",
    "deep-object-diff": "1.1.0",
    "eslint": "^6.7.2",
    "file-saver": "2.0.2",
    "firebase": "7.6.0",
    "font-awesome": "4.7.0",
    "jsoneditor": "8.0.0",
    "jszip": "^3.2.2",
    "lodash": "^4.17.15",
    "merge-deep": "3.0.2",
    "moment": "2.24.0",
    "ng-pick-datetime": "7.0.0",
    "ng-pick-datetime-moment": "1.0.8",
    "ng2-ckeditor": "1.2.6",
    "ng2-img-cropper": "0.9.0",
    "ng2-pdf-viewer": "6.0.2",
    "ngx-chips": "2.1.0",
    "ngx-clipboard": "12.3.0",
    "ngx-device-detector": "1.3.20",
    "ngx-json-viewer": "2.4.0",
    "ngx-webstorage": "4.0.1",
    "rxjs": "6.5.3",
    "string-similarity": "3.0.0",
    "text-encoding": "0.7.0",
    "ts-md5": "1.2.7",
    "web-animations-js": "2.3.2",
    "zone.js": "0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.20",
    "@angular/cli": "8.3.20",
    "@angular/compiler-cli": "8.2.14",
    "@angular/language-service": "8.2.14",
    "@compodoc/compodoc": "^1.1.11",
    "@types/jasmine": "3.5.0",
    "@types/jasminewd2": "2.0.8",
    "@types/jszip": "^3.1.6",
    "@types/lodash": "4.14.149",
    "@types/node": "12.12.20",
    "@types/text-encoding": "0.0.35",
    "chalk": "3.0.0",
    "codelyzer": "5.2.0",
    "diff-json-structure": "^1.0.8",
    "electron": "7.1.5",
    "electron-packager": "14.1.1",
    "jasmine-core": "3.5.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "4.4.1",
    "karma-chrome-launcher": "3.1.0",
    "karma-cli": "2.0.0",
    "karma-coverage-istanbul-reporter": "2.1.1",
    "karma-jasmine": "2.0.1",
    "karma-jasmine-html-reporter": "1.4.2",
    "protractor": "5.4.2",
    "source-map-explorer": "^2.1.2",
    "sw-precache": "5.2.1",
    "ts-node": "8.5.4",
    "tslib": "1.10.0",
    "tslint": "5.20.1",
    "typescript": "3.5.3",
    "webpack-bundle-analyzer": "^3.6.0"
  }
}
`

Hope it helps

**Comment by adamkleingit** [comment]
@monkeywithacupcake - is there a human being listening to mentioning of this user? Is this something you can help with? Thanks

**Comment by adamkleingit** [comment]
@dtomasbar you should be able to bypass this temporarily for the latest version by running:
`npm install --ignore-scripts`
Which disables the postinstall script

**Comment by dtomasbar** [comment]
Thank you very much @adamkleingit

**Comment by monkeywithacupcake** [comment]
You can remove the postinstall entirely. I did in the PR package.json.

**Comment by adamkleingit** [comment]
@monkeywithacupcake I guess that's the easiest solution

**Pull request merged**
