### PR TITLE
fix(api.ts): fix typings for IDTypeDictionary to prevent no implicit any errors

### PR DESCRIPTION
**Pull request by MystK**
I was getting no implicit any errors and this solved it. I verified that everything still works.

### CODE REVIEW

**Comment by adamkleingit** [comment]
Hi,
that could be a problem if the supplied ID is a number and is not backwards compatible.
Do you know why exactly is this solving the implicit any errors?

**Comment by stogle** [comment]
What about `{ [id: string]: boolean, [id: number]: boolean }` instead?

**Comment by adamkleingit** [comment]
@MystK have you tried @stogle 's idea?

**Comment by Melmoth-the-Wanderer** [comment]
I can confirm that @stogle idea fixes the warning: `[ts] Element implicitly has an 'any' type because type 'IDTypeDictionary' has no index signature`,
The warning occurs when you try to assign a property value using brackets notation:
``` typescript
    const rootNodeId = this.nodes[0].id;           
    this.state.activeNodeIds[rootNodeId] = true;
```
It happens when "noImplicitAny" flag is triggered on in tsconfig.

@adamkleingit should I introduce another PR for this or report an issue? It's been inactive for a while.

**Comment by adamkleingit** [comment]
@Melmoth-the-Wanderer if you can push that change I will merge (you can use the same PR).
Thanks

**Comment by Melmoth-the-Wanderer** [comment]
@adamkleingit I've made different PR #645, sorry about that! No idea how to alter existing PR :? <shame on me>

**Comment by Melmoth-the-Wanderer** [comment]
Any idea on release date? :}

**Pull request closed without merging**
