### PR TITLE
[Feature] Angular 12 support

### LINKED ISSUE #915: Angular 12 not  supported
getting this error while upgrading to angular V12  
image

## Minimal reproduction of the bug/regression with instructions:
on angular 11.xx version run command `ng update @angular/core@12 @angular/cli@12`

### PR DESCRIPTION
**Pull request by shanmukhateja**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ X ] The commit message follows our guidelines: https://github.com/CirclonGroup/angular-tree-component/blob/master/CONTRIBUTING.md#commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ X ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Angular 12 support

Closes #915  

## Does this PR introduce a breaking change?

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by shanmukhateja** [comment]
Hi, npm returned error 12 which after quick Googling turned out to be a "out of memory" scenario. I ran the test:ci:local command on my machine and it worked.

Please advice.

**Review by 1shkelzeni — APPROVED** [review]

**Comment by amelnikoff** [comment]
Any news? It's time already for 13.

**Comment by raharrison** [comment]
@tobiasengelhardt Are you able to take a look/get this merged? Currently this component can't be used on Angular 12,13+

**Comment by Mord-Syth** [comment]
Any updates so far? Angular 11 gets out of support in May

**Comment by tobiasengelhardt** [comment]
@raharrison It pains me to see that there is no new development here - but I am not able to help because I don't have the permission to merge. I left the Circlon Group last year. Try reaching someone via os-group@circlon.de

**Comment by bobbyg603** [comment]
hi @shanmukhateja @amelnikoff @raharrison @Mord-Syth @tobiasengelhardt [BugSplat](https://www.bugsplat.com) has [forked](https://github.com/BugSplat-Git/angular-tree-component) this project and added support for Angular 13. We have published a version of this package to [npm](https://www.npmjs.com/package/@bugsplat/angular-tree-component). The [PR](https://github.com/CirclonGroup/angular-tree-component/pull/942) can be seen here.

Hope this helps!

**Comment by piccit** [comment]
Bump... what's the story here, is this repo maintained at all?

**Pull request closed without merging**
