### PR TITLE
Setting option scrollOnActivate to true did not prevent scrolling when clicking a node

### PR DESCRIPTION
**Pull request by amitb00**
See node.setIsActive - calling node.focus with that parameter, but also calling tree.setActiveNode, where node.focus is called without any parameters. Fixed by passing the option there, too (one of those calls might be unnecessary).

### CODE REVIEW

**Comment by harshalnikam** [comment]
Any way to get this PR in to action

**Comment by harshalnikam** [comment]
Any way to get this PR in to action?

**Comment by harshalnikam** [comment]
Any way to get this PR in to action?

**Comment by adamkleingit** [comment]
Published in 8.3.0

**Pull request merged**
